/* Orbit live feed from Cloudflare Worker. */
(()=>{"use strict";
const API="https://orbit-api.tyler-r-theo.workers.dev/feed";
let posts=[],loading=false,error=false,loadedAt=0;
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const tab=()=>document.querySelector(".nav button.active")?.dataset.tab||"Home";
const saved=()=>{try{return JSON.parse(localStorage.getItem("orbit_live_saved")||"[]")}catch{return []}};
const prefs=()=>{try{return JSON.parse(localStorage.getItem("orbit_interests")||"[]")}catch{return []}};
function renderLive(){const main=document.getElementById("main");if(!main)return;document.getElementById("orbit-live")?.remove();const current=tab();if(!["Home","World","Explore","Saved"].includes(current))return;
let list=posts.filter(p=>current!=="Saved"||saved().includes(p.id));
if(current==="World")list=list.filter(p=>/Science|Technology|Business|news|AI/i.test(p.category));
if(current==="Explore")list=list.slice().reverse();
if(current==="Home"){const interests=prefs();list=list.slice().sort((a,b)=>Number(interests.some(t=>a.category.toLowerCase().includes(t.toLowerCase())))-Number(interests.some(t=>b.category.toLowerCase().includes(t.toLowerCase())))) .reverse()}
const section=document.createElement("section");section.id="orbit-live";
let body=loading?'<div class="panel">Loading live stories…</div>':error?'<div class="panel">Could not reach Orbit API. Tap Refresh to retry.</div>':list.length?list.map(p=>{const date=new Date(p.published_at);const dateText=isNaN(date)? "Recent":date.toLocaleString(undefined,{day:"numeric",month:"short",hour:"numeric",minute:"2-digit"});const source=/^https?:\/\//.test(p.source_url||"")?p.source_url:"#";const description=p.summary||"A verified description is not available. Open the original source for details.";return '<article class="post"><div class="posthead"><div class="avatar">↗</div><div><strong>'+esc(p.category||"News")+'</strong><div class="small">'+esc(p.source_name||"Original source")+' · '+esc(dateText)+'</div></div></div><div class="body"><h2>'+esc(p.title)+'</h2><p style="margin:8px 0 12px;line-height:1.5">'+esc(description)+'</p><a class="source" href="'+esc(source)+'" target="_blank" rel="noopener noreferrer">Read original story ↗</a></div><div class="actions"><button data-api-save="'+esc(p.id)+'">'+(saved().includes(p.id)?"▣ Saved":"▢ Save")+'</button><button data-api-share="'+esc(p.id)+'">↗ Share</button></div></article>'}).join(""):'<div class="panel">No live stories in this section yet.</div>';
section.innerHTML='<div class="intro" style="display:flex;align-items:center;justify-content:space-between"><span>Live stories</span><button id="orbit-api-refresh" style="font-size:13px;color:var(--accent)">↻ Refresh</button></div>'+body;main.querySelector(".intro")?.insertAdjacentElement("afterend",section)}
async function load(force=false){if(loading||(!force&&posts.length&&Date.now()-loadedAt<300000))return;loading=true;error=false;renderLive();try{const response=await fetch(API,{cache:"no-store"});if(!response.ok)throw Error("API "+response.status);const data=await response.json();if(!Array.isArray(data.posts))throw Error("Invalid response");posts=data.posts;loadedAt=Date.now()}catch(e){console.warn("Orbit API failed",e);error=true}finally{loading=false;renderLive()}}
document.addEventListener("click",async e=>{if(e.target.closest("#orbit-api-refresh")){load(true);return}const save=e.target.closest("[data-api-save]");if(save){const id=save.dataset.apiSave;const next=new Set(saved());next.has(id)?next.delete(id):next.add(id);localStorage.setItem("orbit_live_saved",JSON.stringify([...next]));renderLive();return}const share=e.target.closest("[data-api-share]");if(share){const p=posts.find(x=>x.id===share.dataset.apiShare);if(!p)return;try{if(navigator.share)await navigator.share({title:p.title,url:p.source_url});else await navigator.clipboard.writeText(p.source_url)}catch{}}});
new MutationObserver(()=>{if(!document.getElementById("orbit-live")&&["Home","World","Explore","Saved"].includes(tab()))renderLive()}).observe(document.getElementById("main"),{childList:true});load();
})();